POST http://localhost:8080/api/v1/todos
Content-Type: application/json
Accept: application/json

{
    "title": "A shorter title",
    "description": "A potentially longer description",
    "assigneeIdList": [1],
    "dueDate": 1633940572720
}

###

POST http://localhost:8080/api/v1/assignees
Content-Type: application/json

{
    "prename": "Ana Cristina",
    "name": "Franco da Silva",
    "email": "ana-cristina.franco-da-silva@iste.uni-stuttgart.de"
}
###
GET http://localhost:8080/api/v1/todos/1
###
POST http://localhost:8080/api/v1/todos
Content-Type: application/json

{
    "title": "A shorter title",
    "description": "A potentially longer description",
    "assigneeIdList": [1],
    "dueDate": 1633940572720
}
###
PUT http://localhost:8080/api/v1/todos/1
Content-Type: application/json

{
   "title": "A shorter title",
   "description": "A potentially longer description",
   "finished": true,
   "assigneeIdList": [1],
   "dueDate": 1633940572720
}

###

DELETE http://localhost:8080/api/v1/todos/1

###
GET http://localhost:8080/api/v1/assignees

###
GET http://localhost:8080/api/v1/assignees/1
###
PUT http://localhost:8080/api/v1/assignees/1
Content-Type: application/json

{
"prename": "Ana Cristina",
"name": "Franco da Silva",
    "email": "ana-cristina.franco-da-silva@iste.uni-stuttgart.de"
}

###
DELETE http://localhost:8080/api/v1/assignees/1
